CREATE DATABASE QLBANTS
go
use QLBANTS
go
--drop table KHACHHANG
CREATE TABLE BAN(
	MABAN	INT	IDENTITY(1,1)	not null,
	TENBAN NVARCHAR(50) NULL,
	SONGUOINGOIMAX INT NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT BAN_PK PRIMARY KEY (MABAN)
)

CREATE TABLE KHUYENMAI(
	MAKM	INT	IDENTITY(1,1) NOT NULL,
	TENKM NVARCHAR(50) NULL,
	SOTIENKM MONEY NULL,
	NGAYBD DATE NULL,
	NGAYKT DATE NULL,
	TRANGTHAI INT NULL,	
	CONSTRAINT KHUYENMAI_PK PRIMARY KEY (MAKM)
)
CREATE TABLE CHUCVU(
	MACV	INT	IDENTITY(1,1)NOT NULL,
	TECV NVARCHAR(50) NULL,
	CONSTRAINT CHUCVU_PK PRIMARY KEY (MACV)
)
CREATE TABLE NCC(
	MANCC	INT	IDENTITY(1,1)NOT NULL,
	TENNCC NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	SDT NVARCHAR(10) NULL,
	CONSTRAINT NCC_PK PRIMARY KEY (MANCC)
)


CREATE TABLE NGUYENLIEU(
	MANL	INT	IDENTITY(1,1) NOT NULL,
	TENNL NVARCHAR(50) NULL,
	MOTA NVARCHAR(50) NULL,
	CONSTRAINT NGUYENLIEU_PK PRIMARY KEY (MANL)
)
CREATE TABLE CALAMVIEC(
	MACLV	INT	IDENTITY(1,1) NOT NULL,
	TENCLV NVARCHAR(50) NULL,
	GIOBD NVARCHAR(20) NULL,
	GIOKT NVARCHAR(20) NULL,
	SOTIEN MONEY NULL,
	CONSTRAINT CALAMVIEC_PK PRIMARY KEY (MACLV)
)
CREATE TABLE USERTT(
	MANV	INT	IDENTITY(1,1) NOT NULL,
	MACV INT NULL,
	HOTEN NVARCHAR(50) NULL,
	GIOITINH NVARCHAR(20) NULL,
	NAMSINH INT NULL,
	DIACHI NVARCHAR(50) NULL,
	CCCD NVARCHAR(12) NULL,
	SDT NVARCHAR(10) NULL,
	TAIKHOAN NVARCHAR(50) unique NULL,
	MATKHAU NVARCHAR(50) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT USERTT_FK FOREIGN KEY (MACV) REFERENCES CHUCVU,
	CONSTRAINT USERTT_PK PRIMARY KEY (MANV)
)
CREATE TABLE LUONGNV(
	MALUONGNV INT IDENTITY(1,1) NOT NULL,
	MACLV INT   NULL,
	MANV INT   NULL,
	TONGSOCALAM INT NULL,
	THANHTIEN MONEY NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,
	FOREIGN KEY (MACLV) REFERENCES CALAMVIEC,
	CONSTRAINT LUONGNV_PK PRIMARY KEY (MALUONGNV)
)
CREATE TABLE KHACHHANG(
	MAKH	INT	IDENTITY(1,1)	PRIMARY KEY,
	TENKH NVARCHAR(20) NULL,
	DIACHI NVARCHAR(20) NULL,
	SDT NVARCHAR(20) NULL,
)
CREATE TABLE HOADON(
	MAHD INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	MAKH INT NULL,
	TINHTRANG INT NULL,
	NGAYTAO DATETIME NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG,		
	CONSTRAINT HOADON_PK PRIMARY KEY (MAHD)
)
CREATE TABLE HOADONNHAPNL(
	MAHDNNL	INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	NGAYNHAP DATE NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,	
	CONSTRAINT HOADONNHAPNL_PK PRIMARY KEY (MAHDNNL)
)
CREATE TABLE CHITIETNHAPNL(
	MACHITIETNNL INT IDENTITY(1,1) NOT NULL,
	MANL INT  NULL,
	MAHDNNL INT  NULL,
	MANCC INT  NULL,
	SOLUONG INT NULL,
	THANHTIEN MONEY NULL,
	FOREIGN KEY (MANL) REFERENCES NGUYENLIEU,	
	FOREIGN KEY (MAHDNNL) REFERENCES HOADONNHAPNL,	
	FOREIGN KEY (MANCC) REFERENCES NCC,	
	CONSTRAINT CHITIETNHAPNL_PK PRIMARY KEY (MACHITIETNNL)
)
CREATE TABLE SANPHAM(
	MASP	INT	IDENTITY(1,1) NOT NULL,
	MAKM INT NULL,
	TENSP NVARCHAR(50) NULL,
	ANHSP VARCHAR(150) NULL,
	GIABAN MONEY NULL,
	TRANGTHAI INT NULL,
	FOREIGN KEY (MAKM) REFERENCES KHUYENMAI,
	CONSTRAINT SANPHAM_PK PRIMARY KEY (MASP)
)
CREATE TABLE COMBO(
	MACOMBO	INT	IDENTITY(1,1) NOT NULL,
	TENCOMBO NVARCHAR(50) NULL,
	GIATIEN MONEY NULL,
	HINHANH NVARCHAR(50) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT COMBO_PK PRIMARY KEY (MACOMBO)
)
CREATE TABLE COMBOCHITIET(
	MACOMBOCT	INT	IDENTITY(1,1) NOT NULL,
	MACOMBO INT  NULL,
	MASP INT  NULL,
	SOLUONG INT NULL,
	FOREIGN KEY (MACOMBO) REFERENCES COMBO,
	FOREIGN KEY (MASP) REFERENCES SANPHAM,
	CONSTRAINT COMBOCHITIET_PK PRIMARY KEY (MACOMBOCT)
)
CREATE TABLE HOADONCHITIET(
	MAHOADONCT	INT	IDENTITY(1,1) NOT NULL,
	MAHD INT  null,
	MASP INT  NULL,
	MABAN INT  NULL,
	SOLUONG INT NULL,
	DONGIA MONEY NULL,
	MOTA NVARCHAR(50) null,
	FOREIGN KEY (MASP) REFERENCES SANPHAM,
	FOREIGN KEY (MABAN) REFERENCES BAN,	
	FOREIGN KEY (MAHD) REFERENCES HOADON,
	CONSTRAINT HOADONCHITIET_PK PRIMARY KEY (MAHOADONCT) 
)
insert into CHUCVU(tecv) values('nhanvien')
insert into USERTT(macv,HOTEN,gioitinh,namsinh,diachi,cccd,sdt,taikhoan,matkhau,trangthai) values(1,'Đinh Đức Đạt','Nam',2003,'hanoi','11212','0129212','tk01','tk02',1)
insert into KHACHHANG(TENKH,DIACHI,SDT) values('Nguyễn Thành Danh','Hà Nội','0385090080')
insert into ban(tenban,songuoingoimax,trangthai) values('Bàn 1',10,0)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM1',1000,'2022-10-12','2022-12-12',1)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM2',2000,'2022-10-12','2022-12-12',1)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM3',3000,'2022-10-12','2022-12-12',1)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(3,'Trà Đào Cam Sả','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\1.png',60000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(3,'Trà Đào Hạnh Phúc','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\1.png',70000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(3,'Trà Sữa','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\2.png',80000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(3,'Tra Chanh','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\3.png',70000,0)

insert into hoadon(manv,makh,tinhtrang,ngaytao) values(1,1,0,'2022-11-12')
insert into hoadon(manv,makh,tinhtrang,ngaytao) values(1,1,0,'2022-11-12')














