CREATE DATABASE QLBANTS
go
use QLBANTS
go
CREATE TABLE KHACHHANG(
	MAKH	INT	IDENTITY(1,1) not null,
	TENKH NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	SDT NVARCHAR(10) NULL,
	CONSTRAINT KHACHHANG_PK PRIMARY KEY (MAKH)
)
CREATE TABLE BAN(
	MABAN	INT	IDENTITY(1,1)	not null,
	TENBAN NVARCHAR(50) NULL,
	SONGUOINGOIMAX INT NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT BAN_PK PRIMARY KEY (MABAN)
)

CREATE TABLE KHUYENMAI(
	MAKM	INT	IDENTITY(1,1) NOT NULL,
	TENKM NVARCHAR(50) NULL,
	SOTIENKM MONEY NULL,
	NGAYBD DATE NULL,
	NGAYKT DATE NULL,
	TRANGTHAI INT NULL,	
	CONSTRAINT KHUYENMAI_PK PRIMARY KEY (MAKM)
)
CREATE TABLE CHUCVU(
	MACV	INT	IDENTITY(1,1)NOT NULL,
	TECV NVARCHAR(50) NULL,
	CONSTRAINT CHUCVU_PK PRIMARY KEY (MACV)
)
CREATE TABLE NCC(
	MANCC	INT	IDENTITY(1,1)NOT NULL,
	TENNCC NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	SDT NVARCHAR(10) NULL,
	CONSTRAINT NCC_PK PRIMARY KEY (MANCC)
)


CREATE TABLE NGUYENLIEU(
	MANL	INT	IDENTITY(1,1) NOT NULL,
	TENNL NVARCHAR(50) NULL,
	MOTA NVARCHAR(50) NULL,
	CONSTRAINT NGUYENLIEU_PK PRIMARY KEY (MANL)
)
CREATE TABLE CALAMVIEC(
	MACLV	INT	IDENTITY(1,1) NOT NULL,
	TENCLV NVARCHAR(50) NULL,
	GIOBD NVARCHAR(20) NULL,
	GIOKT NVARCHAR(20) NULL,
	SOTIEN MONEY NULL,
	CONSTRAINT CALAMVIEC_PK PRIMARY KEY (MACLV)
)
CREATE TABLE USERTT(
	MANV	INT	IDENTITY(1,1) NOT NULL,
	MACV INT NULL,
	HOTEN NVARCHAR(50) NULL,
	GIOITINH NVARCHAR(20) NULL,
	NGAYSINH DATE NULL,
	SDT NVARCHAR(20) NULL,
	TAIKHOAN NVARCHAR(50) NULL,
	MATKHAU NVARCHAR(50) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT USERTT_FK FOREIGN KEY (MACV) REFERENCES CHUCVU,
	CONSTRAINT USERTT_PK PRIMARY KEY (MANV)
)

CREATE TABLE LUONGNV(
	MALUONGNV INT IDENTITY(1,1) NOT NULL,
	MACLV INT   NULL,
	MANV INT   NULL,
	TONGSOCALAM INT NULL,
	THANHTIEN MONEY NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,
	FOREIGN KEY (MACLV) REFERENCES CALAMVIEC,
	CONSTRAINT LUONGNV_PK PRIMARY KEY (MALUONGNV)

)
CREATE TABLE HOADON(
	MAHD INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	MAKH INT NULL,
	TINHTRANG INT NULL,
	NGAYTAO DATE NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG,	
	CONSTRAINT HOADON_PK PRIMARY KEY (MAHD)
)


CREATE TABLE HOADONNHAPNL(
	MAHDNNL	INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	NGAYNHAP DATE NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,	
	CONSTRAINT HOADONNHAPNL_PK PRIMARY KEY (MAHDNNL)
)

CREATE TABLE CHITIETNHAPNL(
	MACHITIETNNL INT IDENTITY(1,1) NOT NULL,
	MANL INT  NULL,
	MAHDNNL INT  NULL,
	MANCC INT  NULL,
	SOLUONG INT NULL,
	THANHTIEN MONEY NULL,
	FOREIGN KEY (MANL) REFERENCES NGUYENLIEU,	
	FOREIGN KEY (MAHDNNL) REFERENCES HOADON,	
	FOREIGN KEY (MANCC) REFERENCES NCC,	
	CONSTRAINT CHITIETNHAPNL_PK PRIMARY KEY (MACHITIETNNL)
)
CREATE TABLE SANPHAM(
	MASP	INT	IDENTITY(1,1) NOT NULL,
	MAKM INT NULL,
	TENSP NVARCHAR(50) NULL,
	GIABAN MONEY NULL,
	TRANGTHAI INT NULL,
	FOREIGN KEY (MAKM) REFERENCES KHUYENMAI,
	CONSTRAINT SANPHAM_PK PRIMARY KEY (MASP)
)

CREATE TABLE COMBO(
	MACOMBO	INT	IDENTITY(1,1) NOT NULL,
	TENCOMBO NVARCHAR(50) NULL,
	GIATIEN MONEY NULL,
	HINHANH NVARCHAR(50) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT COMBO_PK PRIMARY KEY (MACOMBO)
)
CREATE TABLE COMBOCHITIET(
	MACOMBOCT	INT	IDENTITY(1,1) NOT NULL,
	MACOMBO INT  NULL,
	MASP INT  NULL,
	SOLUONG INT NULL,
	FOREIGN KEY (MACOMBO) REFERENCES COMBO,
	FOREIGN KEY (MASP) REFERENCES SANPHAM,
	CONSTRAINT COMBOCHITIET_PK PRIMARY KEY (MACOMBOCT)
)
CREATE TABLE HOADONCHITIET(
	MAHOADONCT	INT	IDENTITY(1,1) NOT NULL,
	MAHD INT  null,
	MASP INT  NULL,
	MABAN INT  NULL,
	MACOMBOCT INT  NULL,
	SOLUONG INT NULL,
	DONGIA MONEY NULL,
	MOTA NVARCHAR(50) null,
	FOREIGN KEY (MASP) REFERENCES SANPHAM,
	FOREIGN KEY (MABAN) REFERENCES BAN,	
	FOREIGN KEY (MAHD) REFERENCES HOADON,
	FOREIGN KEY (MACOMBOCT) REFERENCES COMBOCHITIET,
	CONSTRAINT HOADONCHITIET_PK PRIMARY KEY (MAHOADONCT) 
)
DROP TABLE HOADONCHITIET














