/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17323.view;

import com.poly.it17323.domainmodel.ChucVu;
import com.poly.it17323.reponse.ChucVuReponse;
import com.poly.it17323.repository.ChucVuRepository;
import com.poly.it17323.service.ChucVuService;
import com.poly.it17323.service.impl.ChucVuServiceImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChucVuForm extends javax.swing.JFrame {

    /**
     * Creates new form ChucVuForm
     */
    private ChucVuService ser = new ChucVuServiceImpl();
    private List<ChucVuReponse> reponses = ser.getAll();
    private DefaultTableModel model;
    private int row;

    public ChucVuForm() {
        initComponents();
        txt_ma.disable();
        showData(reponses);
    }

    private void showData(List<ChucVuReponse> list) {
        model = (DefaultTableModel) tbCV.getModel();
        model.setRowCount(0);
        list.forEach(s -> model.addRow(s.toDataRow()));
    }

    private ChucVu getCV() {
        ChucVu cv = new ChucVu();
        cv.setTenCV(txt_tencv.getText());
        return cv;
    }

    private ChucVu getData() {
        int ma = Integer.parseInt(txt_ma.getText());
        String tenCV = txt_tencv.getText();
        return new ChucVu(ma, tenCV);
    }

    private void clear() {
        txt_ma.setText("");
        txt_tencv.setText("");
    }

    private void fillForm() {
        ChucVuReponse cv = reponses.get(row);
        txt_ma.setText(cv.getMaCV().toString());
        txt_tencv.setText(cv.getTenCV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        btnThemDsp = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnUpdateDsp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFindDsp = new javax.swing.JButton();
        btnXoaDsp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCV = new javax.swing.JTable();
        txt_tencv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tên");

        txt_ma.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnThemDsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThemDsp.setText("Thêm");
        btnThemDsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDspActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnUpdateDsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdateDsp.setText("Cập nhật");
        btnUpdateDsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDspActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Tìm theo mã");

        btnFindDsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFindDsp.setText("Tìm kiếm");
        btnFindDsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDspActionPerformed(evt);
            }
        });

        btnXoaDsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaDsp.setText("Xóa");
        btnXoaDsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDspActionPerformed(evt);
            }
        });

        tbCV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbCV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên"
            }
        ));
        tbCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCV);

        txt_tencv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel4.setText("CHUC VU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTim))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ma)
                                    .addComponent(txt_tencv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemDsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateDsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindDsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaDsp)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tencv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDsp)
                    .addComponent(btnUpdateDsp)
                    .addComponent(btnFindDsp)
                    .addComponent(btnXoaDsp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDspActionPerformed
        // TODO add your handling code here:
        String them = ser.add(getCV());
        JOptionPane.showMessageDialog(this, them);
        showData(new ChucVuServiceImpl().getAll());
    }//GEN-LAST:event_btnThemDspActionPerformed

    private void btnUpdateDspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDspActionPerformed
        // TODO add your handling code here:
        ChucVu cv = getData();
        JOptionPane.showMessageDialog(this, ser.update(cv));
        showData(new ChucVuServiceImpl().getAll());
    }//GEN-LAST:event_btnUpdateDspActionPerformed

    private void btnXoaDspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDspActionPerformed
        // TODO add your handling code here:
        row = tbCV.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Xóa không?", "Delete", 0);
            if (choice == JOptionPane.YES_OPTION) {
                ChucVu cv = getData();
                JOptionPane.showMessageDialog(this, ser.delete(cv));
                showData(new ChucVuServiceImpl().getAll());
                clear();
            }
        }
    }//GEN-LAST:event_btnXoaDspActionPerformed

    private void tbCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCVMouseClicked
        // TODO add your handling code here:
//        row = tbCV.getSelectedRow();
//        fillForm();
        int row = tbCV.getSelectedRow();
        txt_ma.setText((String) tbCV.getValueAt(row, 0));
        txt_tencv.setText((String) tbCV.getValueAt(row, 1));
//        txtTenSp.setText((String) tbSp.getValueAt(row, 2));
//        txtGiaBan.setText((String) tbSp.getValueAt(row, 3));
//        if (tbSp.getValueAt(row, 4).equals("Đã hết")) {
//            rdhet.setSelected(true);
//        } else {
//            rdCon.setSelected(true);
//        }
        //        txt_ma.setText((String) tbCV.getValueAt(row, 0));
                //        txt_tencv.setText((String) tbCV.getValueAt(row, 1));
    }//GEN-LAST:event_tbCVMouseClicked

    private void btnFindDspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDspActionPerformed
        // TODO add your handling code here:
        String input = txtTim.getText();
        int count = 0;
        if (input != null) {
            for (int i = 0; i < reponses.size(); i++) {
                if (input.equalsIgnoreCase(reponses.get(i).getMaCV().toString())) {
                    tbCV.setRowSelectionInterval(i, i);
                    count++;
                }
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ko tìm thấy chức vụ");
        }
    }//GEN-LAST:event_btnFindDspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChucVuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindDsp;
    private javax.swing.JButton btnThemDsp;
    private javax.swing.JButton btnUpdateDsp;
    private javax.swing.JButton btnXoaDsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCV;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_tencv;
    // End of variables declaration//GEN-END:variables
}
