/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17323.view;

import com.poly.it17323.domainmodel.KhuyenMai;
import com.poly.it17323.reponse.KhuyenMaiReponse;
import com.poly.it17323.service.KhuyenMaiService;
import com.poly.it17323.service.impl.KhuyenMaiServiceImpl;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KhuyenMaiForm extends javax.swing.JFrame {

    /**
     * Creates new form KhuyenMaiForm
     */
    private KhuyenMaiService khuyenMaiService = new KhuyenMaiServiceImpl();
    private List<KhuyenMaiReponse> reponses = khuyenMaiService.getAll();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private DefaultTableModel model;
    private int row;

    public KhuyenMaiForm() {
        reponses = khuyenMaiService.getAll();
        initComponents();
        showData(reponses);
        txtMa.disable();
    }

    private void showData(List<KhuyenMaiReponse> list) {
        model = (DefaultTableModel) tbKM.getModel();
        model.setRowCount(0);
        list.forEach(s -> model.addRow(s.toDataRow()));
    }

    private KhuyenMai getKM() {
        try {
            KhuyenMai km = new KhuyenMai();
            km.setTenKM(txtTen.getText());
            km.setSoTienKM(Float.parseFloat(txtGiaTri.getText()));
            km.setNgayBD(sdf.parse(txtDate1.getText()));
            km.setNgayKT(sdf.parse(txtDate2.getText()));
            km.setTrangThai(rdApDung.isSelected() ? 0 : 1);
            return km;
        } catch (ParseException ex) {
            return null;
        }
    }

    private KhuyenMai getData() {
        int id = Integer.parseInt(txtMa.getText());
        String tenKM = txtTen.getText();
        float soTienKM = Float.parseFloat(txtGiaTri.getText());
        Date ngayBD = null;
        try {
            ngayBD = sdf.parse(txtDate1.getText());
        } catch (Exception e) {

        }
        Date ngayKT = null;
        try {
            ngayKT = sdf.parse(txtDate2.getText());
        } catch (Exception e) {
        }
        int apDung = rdApDung.isSelected() == true ? 0 : 1;
        return new KhuyenMai(id, tenKM, soTienKM, ngayBD, ngayKT, apDung);
    }

    private void fillForm() {
        KhuyenMaiReponse km = reponses.get(row);
        txtMa.setText(km.getMaKM().toString());
        txtTen.setText(km.getTenKM());
        txtGiaTri.setText(km.getSoTienKM().toString());
        txtDate1.setText(sdf.format(km.getNgayBD()));
        txtDate2.setText(sdf.format(km.getNgayKT()));
        if (tbKM.getValueAt(row, 5).equals("Ngừng áp dụng")) {
            rdNgungAD.setSelected(true);
        } else {
            rdApDung.setSelected(true);
        }
//        tbKM.setRowSelectionInterval(row, row);
    }

    private void clear() {
        txtMa.setText("");
        txtTen.setText("");
        txtDate1.setText("");
        txtDate2.setText("");
        txtGiaTri.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        txtGiaTri = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdApDung = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdNgungAD = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtDate1 = new javax.swing.JTextField();
        txtDate2 = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("VOUCHER KHUYEN MAI");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXoa.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtGiaTri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel2.setText("Mã khuyến mại");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel3.setText("Tên khuyến mại");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel4.setText("Giá trị");

        buttonGroup1.add(rdApDung);
        rdApDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdApDung.setText("Đang áp dụng");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel6.setText("Ngày kết thúc");

        buttonGroup1.add(rdNgungAD);
        rdNgungAD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdNgungAD.setText("Ngừng áp dụng");

        btnThem.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 15)); // NOI18N
        jLabel7.setText("Trạng thái");

        btnSua.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 18)); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtDate1.setMinimumSize(new java.awt.Dimension(7, 23));
        txtDate1.setPreferredSize(new java.awt.Dimension(7, 23));

        txtDate2.setMinimumSize(new java.awt.Dimension(7, 23));
        txtDate2.setPreferredSize(new java.awt.Dimension(7, 23));

        txtMa.setMinimumSize(new java.awt.Dimension(7, 23));
        txtMa.setPreferredSize(new java.awt.Dimension(7, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel4)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdApDung)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdNgungAD)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addGap(31, 31, 31))))
                    .addComponent(txtDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdApDung)
                        .addComponent(rdNgungAD))
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnTim.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 18)); // NOI18N
        btnTim.setText("Tìm khuyến mại");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbKM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KM", "Tên KM", "Giá trị", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ));
        tbKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTim)
                        .addGap(18, 18, 18)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(433, 433, 433))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        //        // TODO add your handling code here:
        row = tbKM.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Xóa không?", "Delete", 0);
            if (choice == JOptionPane.YES_OPTION) {
                KhuyenMai km = getData();
                JOptionPane.showMessageDialog(this, khuyenMaiService.delete(km));
                showData(new KhuyenMaiServiceImpl().getAll());
                clear();
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //        // TODO add your handling code here:
        String them = khuyenMaiService.add(getKM());
        JOptionPane.showMessageDialog(this, them);
        showData(new KhuyenMaiServiceImpl().getAll());
//          showData(khuyenMaiService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        KhuyenMai km = getData();
        JOptionPane.showMessageDialog(this, khuyenMaiService.update(km));
        showData(new KhuyenMaiServiceImpl().getAll());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String input = txtTim.getText();
        int count = 0;
        if (input != null) {
            for (int i = 0; i < reponses.size(); i++) {
                if (input.equalsIgnoreCase(reponses.get(i).getMaKM().toString())) {
                    tbKM.setRowSelectionInterval(i, i);
                    count++;
                }
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ko tìm thấy voucher khuyến mại");
        }

    }//GEN-LAST:event_btnTimActionPerformed

    private void tbKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKMMouseClicked
        // TODO add your handling code here:
        row = tbKM.getSelectedRow();
        KhuyenMaiReponse km = reponses.get(row);
        txtMa.setText(km.getMaKM().toString());
        txtTen.setText(km.getTenKM());
        txtGiaTri.setText(km.getSoTienKM().toString());
        txtDate1.setText(sdf.format(km.getNgayBD()));
        txtDate2.setText(sdf.format(km.getNgayKT()));
        if (tbKM.getValueAt(row, 5).equals("Ngừng áp dụng")) {
            rdNgungAD.setSelected(true);
        } else {
            rdApDung.setSelected(true);
        }

//        int row = tbKM.getSelectedRow();
//        txtMa.setText((String) tbKM.getValueAt(row, 0));
//        txtTen.setText((String) tbKM.getValueAt(row, 1));
//        txtGiaTri.setText((String) tbKM.getValueAt(row, 2));
//        txtDate1.setText(sdf.format(tbKM.getValueAt(row, 3)));
//        txtDate2.setText(sdf.format(tbKM.getValueAt(row, 4)));
//        if (tbKM.getValueAt(row, 5).equals("Ngừng áp dụng")) {
//            rdNgungAD.setSelected(true);
//        } else {
//            rdApDung.setSelected(true);
//        }

//        fillForm();
    }//GEN-LAST:event_tbKMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMaiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMaiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdApDung;
    private javax.swing.JRadioButton rdNgungAD;
    private javax.swing.JTable tbKM;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtDate2;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
